name: "Automatic tagged release"

on:
  push:
    tags:
      - "v*"
jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: build target
        run: mvn install
      - name: build javadoc
        run: mvn javadoc:javadoc
      - name: zip javadoc folder
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r target/site/apidocs.zip target/site/apidocs
      - name: zip jacoco folder
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r target/site/jacoco.zip target/site/jacoco
      - name: build release
        run: |
          echo "done!"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            CODE_OF_CONDUCT.md
            LICENSE
            target/site/apidocs.zip
            target/site/jacoco.zip
            target/boomshot.zip
            target/*.jar
